sudo: required
language: generic
services:
   - docker

before_install:
   - docker build -t steven-weiss/docker-react -f Dockerfile.dev .

script:
   - docker run -e CI=true steven-weiss/docker-react npm run test
