sudo: required
language: generic
services:
   - docker

before_install:
   - docker build -t steven-weiss/docker-react -f Dockerfile.dev .

script:
   - docker run -e CI=true steven-weiss/docker-react npm run test

deploy:
   provider: elasticbeanstalk
   region: "us-east-2"
   app: "docker-react"
   env: "DockerReact-env"
   bucket_name: "elasticbeanstalk-us-east-2-504983352867"
   bucket_path: "docker-react"
   on:
     repo: steven-weiss/docker-react
     branches: 
        only:
           - master
   access_key_id: $AWS_ACCESS_KEY
   secret_access_key:
     secure: $AWS_SECRET
